AppBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: 255
        apellido:
            type: string
            length: 255
        direccion:
            type: string
            length: 255
    lifecycleCallbacks: {  }
